### ISSUE TITLE
v2.0.1: assertion failing in countsArrayIndex

### ISSUE THREAD

**Issue by dominics** [kamino-apm/kamino-reporter#15]
With v2.0.1, the assertion at https://github.com/kamon-io/kamon-apm-reporter/blob/0b9f194666443cd5f260cb8d6817f7fdce0c4059/kamon-apm-reporter/src/main/scala/kamon/apm/package.scala#L86 started to fail. 

Here's the stacktrace:

```
Reporter [Kamon APM Reporter] failed to process a metrics tick.

java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:208)
    at kamon.apm.package$.countsArrayIndex$1(package.scala:86)
    at kamon.apm.package$.countsArrayIndex(package.scala:102)
    at kamon.apm.KamonApm.$anonfun$toIngestionMetricFloatingPointValue$1(KamonApm.scala:169)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at scala.collection.TraversableLike.map(TraversableLike.scala:238)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
    at scala.collection.immutable.List.map(List.scala:298)
    at kamon.apm.KamonApm.toIngestionMetricFloatingPointValue(KamonApm.scala:164)
    at kamon.apm.KamonApm.$anonfun$reportIngestion$5(KamonApm.scala:93)
    at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
    at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
    at scala.collection.immutable.List.flatMap(List.scala:355)
    at kamon.apm.KamonApm.$anonfun$reportIngestion$1(KamonApm.scala:93)
    at kamon.apm.KamonApm.$anonfun$reportIngestion$1$adapted(KamonApm.scala:89)
    at scala.Option.foreach(Option.scala:407)
    at kamon.apm.KamonApm.reportIngestion(KamonApm.scala:89)
    at kamon.apm.KamonApm.reportPeriodSnapshot(KamonApm.scala:60)
    at kamon.module.ModuleRegistry$$anon$1.$anonfun$run$2(ModuleRegistry.scala:176)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
    at scala.util.Success.$anonfun$map$1(Try.scala:255)
    at scala.util.Success.map(Try.scala:213)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

I haven't identified what it is about the metrics we're recording that is triggering the behavior. For now, I'll just be going back to v2.0.0

**Comment by ivantopo** [comment]
Hey man, thanks for reporting this! We fixed via #16 and #17 and just published versions 2.0.2 and 1.1.5 with the fixes. They are on their way to Maven Central now :smile:
