### ISSUE TITLE
Protobuf NPE with tag value null

### ISSUE THREAD

**Issue by StephenKing** [kamino-apm/kamino-reporter#2]
The kamino-reporter triggers a protobuf NPE when one adds a tag with value `null`.. well.. might be reasonable but confused us a bit.

```
ERROR k.ReporterRegistry$Default$MetricReporterTicker    - Reporter [kamon.kamino.KaminoReporter] failed to process a metrics tick.
java.lang.NullPointerException: null
	at shaded.com.google.protobuf.Internal.checkNotNull(Internal.java:67)
	at shaded.com.google.protobuf.MapField$MutatabilityAwareMap.putAll(MapField.java:350)
	at kamino.IngestionV1$Metric$Builder.putAllTags(IngestionV1.java:3320)
	at kamon.kamino.KaminoReporter.kamon$kamino$KaminoReporter$$toIngestionMetricValue(KaminoReporter.scala:117)
	at kamon.kamino.KaminoReporter$$anonfun$reportIngestion$1$$anonfun$3.apply(KaminoReporter.scala:57)
	at kamon.kamino.KaminoReporter$$anonfun$reportIngestion$1$$anonfun$3.apply(KaminoReporter.scala:57)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at kamon.kamino.KaminoReporter$$anonfun$reportIngestion$1.apply(KaminoReporter.scala:57)
	at kamon.kamino.KaminoReporter$$anonfun$reportIngestion$1.apply(KaminoReporter.scala:54)
	at scala.Option.foreach(Option.scala:257)
	at kamon.kamino.KaminoReporter.reportIngestion(KaminoReporter.scala:54)
	at kamon.kamino.KaminoReporter.reportPeriodSnapshot(KaminoReporter.scala:50)
	at kamon.ReporterRegistry$Default$MetricReporterTicker$$anonfun$run$1$$anonfun$apply$3$$anonfun$apply$mcV$sp$7.apply$mcV$sp(ReporterRegistry.scala:344)
	at kamon.ReporterRegistry$Default$MetricReporterTicker$$anonfun$run$1$$anonfun$apply$3$$anonfun$apply$mcV$sp$7.apply(ReporterRegistry.scala:339)
	at kamon.ReporterRegistry$Default$MetricReporterTicker$$anonfun$run$1$$anonfun$apply$3$$anonfun$apply$mcV$sp$7.apply(ReporterRegistry.scala:339)
	at scala.util.Try$.apply(Try.scala:192)
	at kamon.ReporterRegistry$Default$MetricReporterTicker$$anonfun$run$1$$anonfun$apply$3.apply$mcV$sp(ReporterRegistry.scala:338)
	at kamon.ReporterRegistry$Default$MetricReporterTicker$$anonfun$run$1$$anonfun$apply$3.apply(ReporterRegistry.scala:347)
	at kamon.ReporterRegistry$Default$MetricReporterTicker$$anonfun$run$1$$anonfun$apply$3.apply(ReporterRegistry.scala:347)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Code:
```
    HashMap<String, String> tags = new HashMap<>();
    tags.put("test", null);
    Kamon.gauge("foo").refine(tags).increment(1);
```

https://github.com/kamino-apm/kamino-reporter/blob/dc78c15d09e86f321b27a90e193bf06f3e781a1f/src/main/scala/kamon/kamino/KaminoReporter.scala#L117

**Comment by ivantopo** [comment]
Hey @StephenKing, thanks for reporting this one!

So, all in all, from kamon-core we should never allow any null values and created https://github.com/kamon-io/Kamon/issues/518 to track that problem, there I proposed a couple ideas in how to handle this problem, would love to see your feedback on that. Thanks!
