### ISSUE TITLE
BufferUnderflowException when reporting data

### ISSUE THREAD

**Issue by ivantopo** [kamino-apm/kamino-reporter#3]
It is not yet clear under which circumstances this happens but a couple users had the error bellow. Will try to collect information for reproducing the issue.

```
k.ReporterRegistry$Default$MetricReporterTicker - Reporter [loaded-from-config: kamon.kamino.KaminoReporter] failed to process a metrics tick.
java.nio.BufferUnderflowException: null
at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
at java.nio.ByteBuffer.get(ByteBuffer.java:715)
at shaded.com.google.protobuf.ByteString.copyFrom(ByteString.java:351)
at shaded.com.google.protobuf.ByteString.copyFrom(ByteString.java:363)
at kamon.kamino.KaminoReporter.toIngestionMetricDistribution(KaminoReporter.scala:131)
at kamon.kamino.KaminoReporter.$anonfun$reportIngestion$2(KaminoReporter.scala:55)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
at scala.collection.immutable.List.foreach(List.scala:389)
at scala.collection.TraversableLike.map(TraversableLike.scala:234)
at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
```

**Comment by estsauver** [comment]
Hey there! I'm still seeing this on 1.0.0
